### ISSUE TITLE
Write SRS

### ISSUE THREAD

**Issue by aalexsm** [hse-wasd-team/werec#10]
Write the software requirement specification document

**Comment by warkosanta** [comment]
I suggest the following list of **BASE** functions:

- User login/reg (mb we should use only google auth for user managing?)
- Feed creation
- Feed managing (editing, deleting, sharing)
- Feed subscription (how? using unique codes?)

**Comment by warkosanta** [comment]
doc for editing https://docs.google.com/document/d/1Op4fkTgYxKx4lgVwWCFa7iw_J0OcRM8x/edit?usp=sharing&ouid=110617324294000330281&rtpof=true&sd=true

**Comment by aalexsm** [comment]
Added description for sections 2.2-2.6

**Comment by ramilyayus** [comment]
@aalexsm lets close it as version 1 of srs is completed???

**Comment by aalexsm** [comment]
SRS v1.0 is done https://docs.google.com/document/d/1Op4fkTgYxKx4lgVwWCFa7iw_J0OcRM8x/edit?usp=sharing&ouid=110617324294000330281&rtpof=true&sd=true 

Document is to be fixed later, might need opening another issue
