### ISSUE TITLE
Web site design

### ISSUE THREAD

**Issue by ramilyayus** [hse-wasd-team/werec#17]
- In our figma design main web pages of the app 
- Use material design components
- Discuss with team

https://www.figma.com/file/K7WiYoLmLGYdYfAoBcwaKV/WeRec-MUI-design?node-id=4213%3A1335

**Comment by aalexsm** [comment]
Updates from Andrey: https://www.figma.com/file/K7WiYoLmLGYdYfAoBcwaKV/WeRec-MUI-design?node-id=4213%3A1335

**Comment by aalexsm** [comment]
Fixed create feed page (to be discussed)

![Image](https://user-images.githubusercontent.com/71695589/194756824-a221f1e4-23de-41f1-9247-fa12c5427d16.jpg)
![Image](https://user-images.githubusercontent.com/71695589/194756825-b4ad9e56-52d2-4ece-ac12-9b433468ae85.jpg)

**Comment by RipperOnik** [comment]
Fixed create feed page 

![Image](https://user-images.githubusercontent.com/55228345/195149958-e41a485a-876f-49cd-88ff-829412242412.png)


![Image](https://user-images.githubusercontent.com/55228345/195150010-4a88f936-2e78-4e37-913c-af1c23fa1652.png)
