### ISSUE TITLE
Draw sequence diagrams on high-priority UC

### ISSUE THREAD

**Issue by aalexsm** [hse-wasd-team/werec#28]
- [x] Fix existing diagram on "get feed videos" UC
- [x] Add diagram on "create video feed"

Doc for editing: https://drive.google.com/file/d/1FLLhBey6Oe5NJR-MeFCAfY4r-SJ6Zl-T/view?usp=sharing

**Comment by ramilyayus** [comment]
![image](https://user-images.githubusercontent.com/49155262/195980682-9284436e-4742-422c-9ec4-8d2fa99149f7.png)

**Comment by ramilyayus** [comment]
@aalexsm is it all good? can i close the issue?

**Comment by aalexsm** [comment]
@ramilyayus checked, it's valid, thanks
