### ISSUE TITLE
RACI matrix

### ISSUE THREAD

**Issue by zhurbey** [hse-wasd-team/werec#30]
For your project provide & build:

- [x] Create Gantt diagram for your project ;
- [x] RACI Matrix;
- [x] Project management tool (Jira, Redmine, Microsoft Project………..) 
- [x] Task durations and dependencies (SRS==>Tasks)
- [x] Configure Project Plan

RACI Matrix for a software development team.
https://workshopbank.com/raci-matrix

RACI Sample
https://docs.google.com/spreadsheets/d/1YOQX60gdfVCrU0MxbMYmEUvT-NRVN4IM/edit#gid=395204228

**Comment by aalexsm** [comment]
Matrix: https://docs.google.com/spreadsheets/d/1Y8RgDnnYLXJVFkmsLNr0YFN5wbKLlfAb/edit?usp=sharing&ouid=114085712490060538374&rtpof=true&sd=true

Presentation: https://docs.google.com/presentation/d/1bvdqkZCGXjbfPBaW-VmbGODgNzGeZwlqxZNAvnli7Ds/edit?usp=sharing
